# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = "../platforms"

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1113, 775)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(440, 40, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 140, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(36, 340, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(540, 140, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(546, 340, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.btn_Encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Encrypt.setGeometry(QtCore.QRect(130, 440, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_Encrypt.setFont(font)
        self.btn_Encrypt.setObjectName("btn_Encrypt")
        self.btn_Decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Decrypt.setGeometry(QtCore.QRect(300, 440, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_Decrypt.setFont(font)
        self.btn_Decrypt.setObjectName("btn_Decrypt")
        self.btn_Sign = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Sign.setGeometry(QtCore.QRect(640, 440, 75, 23))
        self.btn_Sign.setObjectName("btn_Sign")
        self.btn_Verify = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Verify.setGeometry(QtCore.QRect(810, 440, 75, 23))
        self.btn_Verify.setObjectName("btn_Verify")
        self.btn_GenerateKeys = QtWidgets.QPushButton(self.centralwidget)
        self.btn_GenerateKeys.setGeometry(QtCore.QRect(630, 50, 121, 23))
        self.btn_GenerateKeys.setObjectName("btn_GenerateKeys")
        self.txt_PlainText = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_PlainText.setGeometry(QtCore.QRect(110, 110, 331, 101))
        self.txt_PlainText.setObjectName("txt_PlainText")
        self.txt_Information = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_Information.setGeometry(QtCore.QRect(620, 100, 361, 111))
        self.txt_Information.setObjectName("txt_Information")
        self.txt_CipherText = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_CipherText.setGeometry(QtCore.QRect(120, 320, 321, 91))
        self.txt_CipherText.setObjectName("txt_CipherText")
        self.txt_Signature = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_Signature.setGeometry(QtCore.QRect(620, 320, 361, 101))
        self.txt_Signature.setObjectName("txt_Signature")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1113, 21))
        self.menubar.setObjectName("menubar")
        self.menuRSA_Cipher = QtWidgets.QMenu(self.menubar)
        self.menuRSA_Cipher.setObjectName("menuRSA_Cipher")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuRSA_Cipher.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "RSA CIPHER"))
        self.label_2.setText(_translate("MainWindow", "Plain Text"))
        self.label_3.setText(_translate("MainWindow", "CipherText"))
        self.label_4.setText(_translate("MainWindow", "Information"))
        self.label_5.setText(_translate("MainWindow", "Signature"))
        self.btn_Encrypt.setText(_translate("MainWindow", "Encrypt"))
        self.btn_Decrypt.setText(_translate("MainWindow", "Decrypt"))
        self.btn_Sign.setText(_translate("MainWindow", "Sign"))
        self.btn_Verify.setText(_translate("MainWindow", "Verify"))
        self.btn_GenerateKeys.setText(_translate("MainWindow", "Generate Keys"))
        self.menuRSA_Cipher.setTitle(_translate("MainWindow", "RSA Cipher"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
